name: ns-assembly # define the name of the app

services: # define services
  app: # main Python app
    build: ./ # build using a Dockerfile in the local directory
    depends_on: # delay startup until the DB is ready to accept connections
      db:
        condition: service_healthy
    restart: always # if errors occur, restart
    secrets: # pass secrets to the container
      - bot-token
      - app-db-password
    environment: # pass location of secrets to the container
      ASSEMBLY_TOKEN_FILE: /run/secrets/bot-token
      POSTGRES_PASSWORD_FILE: /run/secrets/app-db-password
      NS_USER_AGENT: idinist_imauggland
    networks: # allow the two containers to communicate
      - app-local

  akari: # akari SSE client
    build: https://github.com/Merethin/Akari.git # build using the latest image from the GitHub repo
    depends_on: # delay startup until the DB is ready to accept connections
      db:
        condition: service_healthy
    restart: always # if errors occur, restart
    secrets: # pass secrets to the container
      - akari-db-password
    environment: # pass connection info to the container
      NS_USER_AGENT: idinist_imauggland
      DATABASE_HOST: ns_assembly_db
      DATABASE_PORT: 5432
      DATABASE_USER: ns_akari
      DATABASE_NAME: ns_akari
      DATABASE_PASSWORD_FILE: /run/secrets/akari-db-password
    networks: # allow the containers to communicate
      - akari-local
    volumes: # bind the config directory into the container
      - ./conf/akari:/config

  db: # postgres DB
    hostname: ns_assembly_db # assign a hostname for easier connection
    image: postgres:18.3-alpine3.23 # use the latest Postgres Alpine image
    shm_size: 128mb # define a memory limit
    restart: always # restart if errors occur
    environment: # pass location of secrets to the container, and define non-secret configuration info
      POSTGRES_PASSWORD_FILE: /run/secrets/sudo-db-password
      APP_PASSWORD_FILE: /run/secrets/app-db-password
      AKARI_PASSWORD_FILE: /run/secrets/akari-db-password
    secrets: # pass secrets to the container
      - app-db-password
      - akari-db-password
      - sudo-db-password
    volumes: # map a volume to the Postgres data directory
      - db-data:/var/lib/postgresql # data
      - ./sql/init:/docker-entrypoint-initdb.d # initialization scripts
    networks: # allow the two containers to communicate
      - app-local
      - akari-local
    healthcheck: # set up a health check to confirm when the DB is ready
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
secrets:  # define secrets
  bot-token:
    file: ./conf/secrets/token.conf
  app-db-password:
    file: ./conf/secrets/appdb.conf
  akari-db-password:
    file: ./conf/secrets/akaridb.conf
  sudo-db-password:
    file: ./conf/secrets/sudodb.conf
  
volumes: # allow Docker to handle volume storage
  db-data:

networks: # allow Docker to handle networking
  app-local:
  akari-local: